version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

  node-api-1:
    build: .
    container_name: node-api-1
    restart: always
    ports:
      - 9001:9001
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017
      PORT: 9001

  node-api-2:
    build: .
    container_name: node-api-2
    restart: always
    ports:
      - 9002:9002
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017
      PORT: 9002

  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    restart: always
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    environment:
      NGINX_LOG_LEVEL: DEBUG