version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
  node-api-1:
    build: .
    container_name: node-api-1
    restart: always
    ports:
      - 9000:9000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017